### ISSUE TITLE
Add Linting, Tests, Code Coverage, and CI

### ISSUE THREAD

**Issue by fedorareis** [CruCentralCoast/Keystone#41]
In order to ensure that the server continues to operate smoothly certain things need to be put in place. 

We will be adding eslint as the linter for the project. This will make code review easier, reducing the number of formatting corrections that will need to be made. It will also help catch common issues.

Tests will need to be added to the project. Currently, I am looking at using mocha/chai to achieve this as they appear to be the common standard for JS testing.

I would also like to add Code Coverage, largely as a means of understanding how much of our code is or is not tested.

We will be hooking all of this up to a CI (Continuous Integration) system. We will start by using CircleCI and if that doesn't fit our needs we will move to something else. CI will be linked into pull requests and merges will not occur unless the merge passes CI.

This is all being implemented to help prevent changes to the server from breaking the app and website.

## Tasks
- [x] Configure eslint
- [x] Set up CircleCI
- [ ] Start writing tests using mocha/chai
- [ ] Find and setup a Code Coverage tool

**Comment by fedorareis** [comment]
Initial eslint configuration is set up and pulled in as of #39 

Initial CircleCI configuration set up as of #40
